[project]
name = "react-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muhammad Junaid", email = "mr.junaidshaukat@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain-google-genai>=2.0.9",
    "langgraph>=0.2.74",
    "python-dotenv>=1.0.1",
]

[project.scripts]
react-agent = "react_agent:main"
prebuilt = "react_agent.prebuilt:main"
custom = "react_agent.custom:main"
prebuilt_w_tools = "react_agent.prebuilt_w_tools:main"
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
