[project]
name = "patterns-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muhammad Junaid", email = "mr.junaidshaukat@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "autogen-agentchat>=0.4.7",
    "autogen-ext[openai]>=0.4.7",
    "python-dotenv>=1.0.1",
]

[project.scripts]
patterns-code = "patterns_code:main"
handoff = "patterns_code.handoff:main"
routine = "patterns_code.routine:main"
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
